services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./database/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./database/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $USER
      POSTGRES_PASSWORD: $PASSWORD
      POSTGRES_DB: $DATABASE
  api:
    build: ./server
    ports:
      - "56534:56534"
  webapp:
    build: ./webapp
    ports:
      - "8080:8080"
