services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  api:
    build: ./server
    ports:
      - "56534:56534"
  web:
    build: ./webapp
    ports:
      - "8080:8080"