services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./database/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./database/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SCHEMA: ${POSTGRES_SCHEMA}
  api:
    build: ./server
    ports:
      - "56534:56534"
  web:
    build: ./webapp
    ports:
      - "8080:8080"